/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Class.Authentification;
import ClassDAO.AuthentificationDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author alexis
 */
public class AuthentificationForm extends javax.swing.JFrame {

    /**
     * Creates new form Authentification
     */
    public AuthentificationForm() {
        initComponents();
        MessageInvisible();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jTextField_adresseMail = new javax.swing.JTextField();
        jLabel_adresseMail = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jButton_connexion = new javax.swing.JButton();
        jLabel_message_errreur_connexion = new javax.swing.JLabel();
        jTextField_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);

        jLabel_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel_Image.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_Image.setMaximumSize(new java.awt.Dimension(620, 250));
        jLabel_Image.setMinimumSize(new java.awt.Dimension(620, 250));

        jTextField_adresseMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_adresseMailActionPerformed(evt);
            }
        });

        jLabel_adresseMail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_adresseMail.setText("Adresse Mail :");

        jLabel_password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_password.setText("Mot de passe :");

        jButton_connexion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_connexion.setText("Connexion");
        jButton_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_connexionActionPerformed(evt);
            }
        });

        jLabel_message_errreur_connexion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_message_errreur_connexion.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_message_errreur_connexion.setText("Couple login / mot de passe incorrecte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_message_errreur_connexion)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_password)
                            .addComponent(jLabel_adresseMail))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_adresseMail, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextField_password))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_adresseMail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_adresseMail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_message_errreur_connexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton_connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_adresseMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_adresseMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_adresseMailActionPerformed

    private void jButton_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_connexionActionPerformed
 
        String driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://127.0.01:3306/megacasting";
        String utilisateur = "root";
        String password = "";      

        Connection cnx = null;

        Boolean erreur = true;

        //Vérification champs renseigné.
        if(jTextField_adresseMail.getText().equals("")){
            jTextField_adresseMail.setVisible(true);
            erreur = false;
        }
        if(jTextField_password.getText().equals("")){
            jTextField_password.setVisible(true);
            erreur = false;
        }

        if(erreur == true){
            try {
                cnx = DriverManager.getConnection(url, utilisateur, password);

                System.out.println("Connexion réussi !");

                Authentification authentification = new Authentification(jTextField_adresseMail.getText(), jTextField_password.getText());
                Boolean connexion_ok = AuthentificationDAO.Connexion(cnx, authentification);

                if(connexion_ok == true){
                    System.out.println("Connexion accepté !");
                    System.out.println("Connexion fermé !");
                    this.setVisible(false);
                    MaFenetrePrincipale jframe = new MaFenetrePrincipale();
                    jframe.setVisible(true);
                }else{
                    System.out.println("Connexion refusé !");
                    AuthentificationForm.jLabel_message_errreur_connexion.setVisible(true);
                    //Effacé les champs + message erreur.
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }finally{

                if(cnx != null){
                    try {
                        cnx.close();
                    } catch (SQLException ex) {
                    }
                }
            }

            System.out.println("Connexion fermé !");
            jTextField_adresseMail.setText("");
            jTextField_password.setText("");
        }

    }//GEN-LAST:event_jButton_connexionActionPerformed

    
    private void MessageInvisible(){
        AuthentificationForm.jLabel_message_errreur_connexion.setVisible(false);      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthentificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthentificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthentificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthentificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthentificationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton_connexion;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_adresseMail;
    public static javax.swing.JLabel jLabel_message_errreur_connexion;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JTextField jTextField_adresseMail;
    private javax.swing.JPasswordField jTextField_password;
    // End of variables declaration//GEN-END:variables
}
