/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Class.Annonceur;
import ClassDAO.AnnonceurDAO;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Collection;

/**
 *
 * @author alexis
 */
public class RedirectionForm extends javax.swing.JPanel {

    private MaFenetrePrincipale mafenetreprincipal;
    
    public RedirectionForm(MaFenetrePrincipale maFenetrePrincipale){
        this.mafenetreprincipal = maFenetrePrincipale;
        initComponents();
    }
    /**
     * Creates new form RedirectionForm1
     */
    public RedirectionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jButton_redirection_annonce_ligne = new javax.swing.JButton();
        jButton_redirection_nouvelles_annonces = new javax.swing.JButton();

        jLabel_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel_Image.setMaximumSize(new java.awt.Dimension(620, 250));
        jLabel_Image.setMinimumSize(new java.awt.Dimension(620, 250));

        jButton_redirection_annonce_ligne.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_redirection_annonce_ligne.setForeground(new java.awt.Color(51, 51, 51));
        jButton_redirection_annonce_ligne.setText("Gérer les annonces en ligne");
        jButton_redirection_annonce_ligne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_redirection_annonce_ligneActionPerformed(evt);
            }
        });

        jButton_redirection_nouvelles_annonces.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_redirection_nouvelles_annonces.setForeground(new java.awt.Color(51, 51, 51));
        jButton_redirection_nouvelles_annonces.setText("Nouvelles annonces");
        jButton_redirection_nouvelles_annonces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_redirection_nouvelles_annoncesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_redirection_annonce_ligne, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_redirection_nouvelles_annonces, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_redirection_annonce_ligne, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_redirection_nouvelles_annonces, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_redirection_annonce_ligneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_redirection_annonce_ligneActionPerformed
        CardLayout c1 = (CardLayout) MaFenetrePrincipale.Panel_principal.getLayout();
        c1.show(MaFenetrePrincipale.Panel_principal, "acceuilCard");
    }//GEN-LAST:event_jButton_redirection_annonce_ligneActionPerformed

    private void jButton_redirection_nouvelles_annoncesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_redirection_nouvelles_annoncesActionPerformed
        CardLayout c1 = (CardLayout) MaFenetrePrincipale.Panel_principal.getLayout();
        c1.show(MaFenetrePrincipale.Panel_principal, "newannonceCard");
    }//GEN-LAST:event_jButton_redirection_nouvelles_annoncesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_redirection_annonce_ligne;
    private javax.swing.JButton jButton_redirection_nouvelles_annonces;
    private javax.swing.JLabel jLabel_Image;
    // End of variables declaration//GEN-END:variables
}
