/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Class.Annonceur;
import Class.Contrat;
import Class.Diffuseur;
import Class.Domaine;
import Class.Media;
import Class.Metier;
import Class.Offre;
import ClassDAO.AnnonceurDAO;
import ClassDAO.ContratDAO;
import ClassDAO.DiffuseurDAO;
import ClassDAO.DomaineDAO;
import ClassDAO.MediaDAO;
import ClassDAO.MetierDAO;
import ClassDAO.OffreDAO;
import static View.OffreForm.jComboBox_annonceur;
import static View.OffreForm.jComboBox_contrat;
import static View.OffreForm.jComboBox_diffuseur;
import static View.OffreForm.jComboBox_domaine;
import static View.OffreForm.jComboBox_media;
import static View.OffreForm.jComboBox_metier;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author alexis
 */
public class ValidationForm extends javax.swing.JPanel {

    private MaFenetrePrincipale mafenetreprincipal;
    
    public ValidationForm(MaFenetrePrincipale maFenetrePrincipale){
        this.mafenetreprincipal = maFenetrePrincipale;
        initComponents();
        jLabel_message_erreur.setVisible(false);
        jLabel_message_valider.setVisible(false);
    }
    
    /**
     * Creates new form ValidationForm
     */
    public ValidationForm() {
        initComponents();
    }
    
    public void test(Offre off){

        jLabel_identifiant_annonce.setText(Long.toString(off.getId_offre()));
        jLabel_intitule_annonce.setText(off.getInt_offre());
        jLabel_reference_annonce.setText(off.getRef_offre());
        jLabel_date_casting_annonce.setText(off.getDate_offre());
        jLabel_duree_annonce.setText(Long.toString(off.getDuree_offre()));
        jLabel_date_debut_annonce.setText(off.getDate_deb_offre());
        jLabel_localisation_annonce.setText(off.getLoc_offre());
        jLabel_metier_annonce.setText(off.getMetier().getLib_metier());      
        jLabel_description_annonce.setText(off.getDesc_offre());
        jLabel_annonceur_annonce.setText(off.getAnnonceur().getNom_annonceur());
        jLabel_contrat_annonce.setText(off.getContrat().getLib_contrat());
        jLabel_domaine_annonce.setText(off.getDomaine().getLib_domaine());
        jLabel_media_annonce.setText(off.getMetier().getLib_metier());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always.
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel79 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jButton_retour_ajouter_annonceur4 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jButton_validation_annonce = new javax.swing.JButton();
        jLabel_intitule_annonce = new javax.swing.JLabel();
        jLabel_identifiant_annonce = new javax.swing.JLabel();
        jLabel_reference_annonce = new javax.swing.JLabel();
        jLabel_date_casting_annonce = new javax.swing.JLabel();
        jLabel_date_debut_annonce = new javax.swing.JLabel();
        jLabel_duree_annonce = new javax.swing.JLabel();
        jLabel_metier_annonce = new javax.swing.JLabel();
        jLabel_localisation_annonce = new javax.swing.JLabel();
        jLabel_description_annonce = new javax.swing.JLabel();
        jLabel_contrat_annonce = new javax.swing.JLabel();
        jLabel_domaine_annonce = new javax.swing.JLabel();
        jLabel_annonceur_annonce = new javax.swing.JLabel();
        jLabel_media_annonce = new javax.swing.JLabel();
        jLabel_message_erreur = new javax.swing.JLabel();
        jCheckBox_valider = new javax.swing.JCheckBox();
        jLabel_message_valider = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel79.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(204, 204, 204));
        jLabel79.setText("Identifiant :");

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(204, 204, 204));
        jLabel65.setText("Intitulé :");

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(204, 204, 204));
        jLabel66.setText("référence :");

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(204, 204, 204));
        jLabel69.setText("date casting :");

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(204, 204, 204));
        jLabel67.setText("durée :");

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(204, 204, 204));
        jLabel68.setText("date début :");

        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(204, 204, 204));
        jLabel70.setText("Localisation :");

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(204, 204, 204));
        jLabel71.setText("Description de l'offre :");

        jLabel74.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(204, 204, 204));
        jLabel74.setText("Metier :");

        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(204, 204, 204));
        jLabel72.setText("Annonceur :");

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(204, 204, 204));
        jLabel73.setText("Contrat :");

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(204, 204, 204));
        jLabel75.setText("Domaine :");

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(204, 204, 204));
        jLabel76.setText("Media :");

        jButton_retour_ajouter_annonceur4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_retour_ajouter_annonceur4.setForeground(new java.awt.Color(51, 51, 51));
        jButton_retour_ajouter_annonceur4.setText("Retour");
        jButton_retour_ajouter_annonceur4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_retour_ajouter_annonceur4ActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(204, 204, 204));
        jLabel48.setText("Résumé des informations de l'annonce");

        jButton_validation_annonce.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_validation_annonce.setForeground(new java.awt.Color(51, 51, 51));
        jButton_validation_annonce.setText("Valider");
        jButton_validation_annonce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_validation_annonceActionPerformed(evt);
            }
        });

        jLabel_intitule_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_intitule_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_intitule_annonce.setText("text");

        jLabel_identifiant_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_identifiant_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_identifiant_annonce.setText("text");

        jLabel_reference_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_reference_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_reference_annonce.setText("text");

        jLabel_date_casting_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_date_casting_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_date_casting_annonce.setText("text");

        jLabel_date_debut_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_date_debut_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_date_debut_annonce.setText("text");

        jLabel_duree_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_duree_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_duree_annonce.setText("text");

        jLabel_metier_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_metier_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_metier_annonce.setText("text");

        jLabel_localisation_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_localisation_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_localisation_annonce.setText("text");

        jLabel_description_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_description_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_description_annonce.setText("text");

        jLabel_contrat_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_contrat_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_contrat_annonce.setText("text");

        jLabel_domaine_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_domaine_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_domaine_annonce.setText("text");

        jLabel_annonceur_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_annonceur_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_annonceur_annonce.setText("text");

        jLabel_media_annonce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_media_annonce.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_media_annonce.setText("text");

        jLabel_message_erreur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_message_erreur.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_message_erreur.setText("X");

        jCheckBox_valider.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox_valider.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_valider.setText("Valider l'annonce");

        jLabel_message_valider.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_message_valider.setForeground(new java.awt.Color(0, 153, 51));
        jLabel_message_valider.setText("L'annonce a bien été validé.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel48)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 99, Short.MAX_VALUE)
                                .addComponent(jButton_retour_ajouter_annonceur4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel68)
                                                .addComponent(jLabel70)
                                                .addComponent(jLabel74)
                                                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(44, 44, 44)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel_duree_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                .addComponent(jLabel_date_debut_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel_localisation_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel_metier_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel69)
                                                .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(39, 39, 39)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel_intitule_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel_identifiant_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel_reference_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel_date_casting_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_message_erreur)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel73))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel_contrat_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel_domaine_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel72)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel_annonceur_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel71)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel_media_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jButton_validation_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_description_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_message_valider))
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel48)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_identifiant_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_intitule_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_reference_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_date_casting_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel_description_annonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_annonceur_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_duree_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_date_debut_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_contrat_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_localisation_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_domaine_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_metier_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_media_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_message_erreur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_valider)
                    .addComponent(jLabel_message_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_validation_annonce, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_retour_ajouter_annonceur4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_retour_ajouter_annonceur4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_retour_ajouter_annonceur4ActionPerformed
        CardLayout c1 = (CardLayout) MaFenetrePrincipale.Panel_principal.getLayout();
        c1.show(MaFenetrePrincipale.Panel_principal, "newannonceCard");
    }//GEN-LAST:event_jButton_retour_ajouter_annonceur4ActionPerformed

    private void jButton_validation_annonceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_validation_annonceActionPerformed
       
        jLabel_message_erreur.setVisible(false);
        jLabel_message_valider.setVisible(false);
        
        if (jCheckBox_valider.isSelected()) {
            
            String driver = "com.mysql.jdbc.Driver";
            String url = "jdbc:mysql://127.0.0.1/megacasting";
            String utilisateur = "root";
            String password = "";                    

            Connection cnx = null;             

             try {
                 cnx = DriverManager.getConnection(url, utilisateur, password);

                 System.out.println("Connexion réussi !"); 
                 System.out.println(jLabel_identifiant_annonce.getText());
                 int Validation = 0;
                 Annonceur annonceur = AnnonceurDAO.TrouverAnnonceurNom(cnx, jLabel_annonceur_annonce.getText());
                 Contrat contrat = ContratDAO.TrouverContratNom(cnx, jLabel_contrat_annonce.getText());
                 Metier metier = MetierDAO.TrouverMetierNom(cnx, jLabel_metier_annonce.getText());
                 Domaine domaine = DomaineDAO.TrouverDomaineNom(cnx, jLabel_domaine_annonce.getText());          
                 Media media = MediaDAO.TrouverMediaUrl(cnx, jLabel_media_annonce.getText());

                 Offre off = new Offre(jLabel_intitule_annonce.getText(), jLabel_reference_annonce.getText(), jLabel_date_casting_annonce.getText(), Integer.parseInt(jLabel_duree_annonce.getText().toString()), jLabel_date_debut_annonce.getText(), jLabel_localisation_annonce.getText(), jLabel_description_annonce.getText(), Validation, annonceur, contrat, metier, domaine);
                 off.setId_offre(Integer.parseInt(jLabel_identifiant_annonce.getText()));
                 OffreDAO.ValiderOffre(cnx, off);

                 NewAnnonceForm.ListerNewAnnonce();
                 jLabel_message_valider.setVisible(true);

             } catch (Exception ex) {
                 ex.printStackTrace();
             }finally{

                 if(cnx != null){
                     try {
                         cnx.close();
                     } catch (SQLException ex) {
                     }
                 }
             }

             System.out.println("Connexion fermé !"); 
        
        } else {
            jLabel_message_erreur.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton_validation_annonceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_retour_ajouter_annonceur4;
    private javax.swing.JButton jButton_validation_annonce;
    private javax.swing.JCheckBox jCheckBox_valider;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel_annonceur_annonce;
    private javax.swing.JLabel jLabel_contrat_annonce;
    private javax.swing.JLabel jLabel_date_casting_annonce;
    private javax.swing.JLabel jLabel_date_debut_annonce;
    private javax.swing.JLabel jLabel_description_annonce;
    private javax.swing.JLabel jLabel_domaine_annonce;
    private javax.swing.JLabel jLabel_duree_annonce;
    private javax.swing.JLabel jLabel_identifiant_annonce;
    private javax.swing.JLabel jLabel_intitule_annonce;
    private javax.swing.JLabel jLabel_localisation_annonce;
    private javax.swing.JLabel jLabel_media_annonce;
    public static javax.swing.JLabel jLabel_message_erreur;
    public static javax.swing.JLabel jLabel_message_valider;
    private javax.swing.JLabel jLabel_metier_annonce;
    private javax.swing.JLabel jLabel_reference_annonce;
    // End of variables declaration//GEN-END:variables
}
